version: "3.8"

services:
  django:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BACKEND_NAME: ${BACKEND_NAME}
    ports:
      - "8000:8000"
    volumes:
      - django:/home/transcendance
    tty: true
    # networks:
    #   - pong
    init: true

volumes:
  django:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      # device: '/Users/apalumbi/Documents/apalumbi_git/6_transcendance/backend' # school
      device: "/Users/alesspal/Documents/42/6_ft_transcendance_git/backend" # home

# networks:
#   pong:
#     driver: bridge
